---
apiVersion: v1
kind: Secret
metadata:
  name: hafenmeister
  namespace: flux-system
stringData:
  address: {{ inbound_url_base64 }}

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: hafenmeister
  namespace: flux-system
spec:
  type: generic
  channel: general
  secretRef:
    name: hafenmeister

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: hafenmeister
  namespace: flux-system
spec:
  providerRef:
    name: hafenmeister
  eventSeverity: info
  eventSources:
    - kind: Bucket
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmChart
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: ImageRepository
      name: '*'
    - kind: ImagePolicy
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
