{{- if eq (include "hafenmeister.staticfiles.enabled" . ) "true" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hafenmeister.staticfiles.fullname" . }}
  labels:
    {{- include "hafenmeister.labels.staticfiles" . | nindent 4 }}
spec:
  replicas: {{ .Values.component.staticfiles.replicaCount }}
  strategy:
    {{ toYaml .Values.component.staticfiles.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "hafenmeister.selectorLabels.staticfiles" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.component.staticfiles.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hafenmeister.selectorLabels.staticfiles" . | nindent 8 }}
    spec:
      {{- with (default .Values.component.staticfiles.imageConfig.pullSecrets .Values.global.imageConfig.pullSecrets ) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hafenmeister.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.component.staticfiles.podSecurityContext | nindent 8 }}
      containers:
        - name: staticfiles
          securityContext:
            {{- toYaml .Values.component.staticfiles.securityContext | nindent 12 }}
          image: "{{ if hasKey .Values.component.staticfiles "image" }}{{ .Values.component.staticfiles.image }}{{ else }}{{ .Values.global.images.staticfiles }}{{ end }}"
          imagePullPolicy: {{ .Values.component.staticfiles.imageConfig.pullPolicy }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.component.staticfiles.resources | nindent 12 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
      {{- with .Values.component.staticfiles.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.component.staticfiles.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.component.staticfiles.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "hafenmeister.selectorLabels.staticfiles" . | nindent 14 }}
{{- end }}
