{{- if eq (include "hafenmeister.staticfiles.enabled" . ) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hafenmeister.staticfiles.fullname" . }}
  labels:
    {{- include "hafenmeister.labels.staticfiles" . | nindent 4 }}
spec:
  type: {{ .Values.component.staticfiles.service.type }}
  ports:
    - port: {{ .Values.component.staticfiles.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hafenmeister.selectorLabels.staticfiles" . | nindent 4 }}
{{- end }}
