# Generated by Django 3.2.10 on 2021-12-28 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxWebhookTransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_received', models.DateTimeField(auto_now_add=True, verbose_name='received')),
                ('datetime_processed', models.DateTimeField(editable=False, null=True, verbose_name='processed')),
                ('status', models.IntegerField(choices=[(0, 'unprocessed'), (1, 'processed'), (2, 'error')], default=0)),
                ('request_meta', models.JSONField(editable=False)),
                ('request_body', models.JSONField(editable=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_transactions', to='flux.fluxclustermodel', verbose_name='cluster')),
            ],
            options={
                'verbose_name': 'Webhook Transaction',
                'verbose_name_plural': 'Webhook Transactions',
            },
        ),
    ]
