# Generated by Django 3.2.10 on 2021-12-29 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_auto_20211228_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxobjectmodel',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AlterField(
            model_name='fluxobjectmodel',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_objects', to='flux.fluxclustermodel', verbose_name='cluster'),
        ),
        migrations.AlterField(
            model_name='fluxobjectmodel',
            name='object_apiVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_objects', to='flux.fluxobjectapiversionmodel', verbose_name='api version'),
        ),
        migrations.AlterField(
            model_name='fluxobjectmodel',
            name='object_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_objects', to='flux.fluxobjectkindmodel', verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='fluxobjectmodel',
            name='object_namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_objects', to='flux.fluxobjectnamespacemodel', verbose_name='namespace'),
        ),
        migrations.CreateModel(
            name='FluxEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=254, verbose_name='reason')),
                ('message', models.TextField(verbose_name='message')),
                ('severity', models.CharField(choices=[('info', 'info'), ('error', 'error')], max_length=10, verbose_name='severity')),
                ('datetime_timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='flux.fluxobjectmodel', verbose_name='object')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
    ]
