# Generated by Django 3.2.10 on 2021-12-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_auto_20211229_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxobjectmodel',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Object'},
        ),
    ]
