# Generated by Django 3.2.10 on 2021-12-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0006_fluxeventmodel_associated_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxclustermodel',
            options={'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterModelOptions(
            name='fluxeventmodel',
            options={'ordering': ['-datetime_timestamp'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='fluxobjectmodel',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='fluxwebhooktransactionmodel',
            options={'ordering': ['-datetime_received'], 'verbose_name': 'Webhook Transaction', 'verbose_name_plural': 'Webhook Transactions'},
        ),
    ]
