#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app --disable-redirect-access-to-syslog --access-logfile - --access-logformat="%({x-forwarded-for}i)s '%(r)s %(s)s' %(l)s %(b)s %(D)s %(l)s %(a)s"
