# Generated by Django 3.2.10 on 2022-02-08 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=254, unique=True, verbose_name='device id')),
            ],
        ),
        migrations.CreateModel(
            name='SensorsMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestemp', models.DateTimeField(verbose_name='timestamp')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='temperature')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='humidity')),
                ('battery', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='battery')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors_measurements', to='sensors.sensorsdevice', verbose_name='device')),
            ],
        ),
    ]
