---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hafenmeister.django.fullname" . }}
  labels:
    {{- include "hafenmeister.labels.django" . | nindent 4 }}
spec:
  type: {{ .Values.component.django.service.type }}
  ports:
    - port: {{ .Values.component.django.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hafenmeister.selectorLabels.django" . | nindent 4 }}
