---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hafenmeister.fullname" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
data:
  {{- range $index, $value := .Values.global.configs }}
    {{ $index }}: {{ $value | quote }}
  {{- end }}
