---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hafenmeister.fullname" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $index, $value := .Values.global.secrets }}
    {{ $index }}: {{ b64enc $value }}
  {{- end }}
