# Generated by Django 3.2.10 on 2021-12-28 11:23

from django.db import migrations
import hafenmeister.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersusermodel',
            managers=[
                ('objects', hafenmeister.users.models.UsersUserManager()),
            ],
        ),
    ]
