{{- if .Values.global.networkPolicy.create }}
{{- if eq (include "hafenmeister.staticfiles.enabled" . ) "true" }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "hafenmeister.networkPolicy.staticfiles.allowFromExternal" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hafenmeister.selectorLabels.staticfiles" . | nindent 8 }}
  ingress:
  - from: {{ toYaml .Values.global.networkPolicy.allowAccessFrom | nindent 6 }}
    ports:
    - protocol: TCP
      port: {{ .Values.component.staticfiles.service.port }}
{{- end }}
{{- end }}
