{{- if .Values.global.networkPolicy.create }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hafenmeister.networkPolicy.postgresql.allowAccess" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      application: spilo
      cluster-name: {{ include "hafenmeister.postgresql.fullname" . }}
      team: {{ include "hafenmeister.fullname" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          needs-psql-access: "yes"
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
    ports:
    - port: 5432
      protocol: TCP
  policyTypes:
  - Ingress
{{- end }}
