{{- if .Values.global.networkPolicy.create }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "hafenmeister.networkPolicy.django.allowFromExternal" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hafenmeister.selectorLabels.django" . | nindent 8 }}
  ingress:
  - from: {{ toYaml .Values.global.networkPolicy.allowAccessFrom | nindent 6 }}
    ports:
    - protocol: TCP
      port: {{ .Values.component.django.service.port }}
{{- end }}
