{{- if .Values.global.networkPolicy.create }}
{{- if .Values.component.celeryflower.serviceMonitor.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "hafenmeister.networkPolicy.celeryflower.allowMetricFromExternal" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hafenmeister.selectorLabels.celeryflower" . | nindent 8 }}
  ingress:
  - from: {{ toYaml .Values.global.networkPolicy.allowMetricAccessFrom | nindent 6 }}
    ports:
    - protocol: TCP
      port: {{ .Values.component.celeryflower.service.port }}
{{- end }}
{{- end }}
