{{- if .Values.global.networkPolicy.create }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "hafenmeister.networkPolicy.rabbitmq.cross" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hafenmeister.rabbitmq.fullname" . }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ template "hafenmeister.rabbitmq.fullname" . }}
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 15672
        - protocol: TCP
          port: 15692
        - protocol: TCP
          port: 4369
        - protocol: TCP
          port: 25672
{{- end }}
