{{- if .Values.global.networkPolicy.create }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hafenmeister.networkPolicy.defaultDeny" . }}
  labels:
{{ include "hafenmeister.labels" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
