---

name: Build & Deploy
on: [push]

env:
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Authenticate with Docker registry
        run: echo $HARBOR_PASSWORD | docker login harbor.modac.cloud -u $HARBOR_USERNAME --password-stdin

      - name: Install skaffold
        run: curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install /tmp/skaffold /usr/local/bin/

      - name: Run skaffold build
        run: skaffold build -p production --file-output=skaffold-images.json

      - name: 'Upload Skaffold Images Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: skaffold-images
          path: skaffold-images.json


  deploy_to_production:
    name: Deploy to Production
    needs: Build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download Skaffold Images Artifact
        uses: actions/download-artifact@v2
        with:
          name: skaffold-images

      - name: Authenticate with Docker registry
        run: echo $HARBOR_PASSWORD | docker login harbor.modac.cloud -u $HARBOR_USERNAME --password-stdin

      - name: Run skaffold deploy (production)
        run: chmod +x ./skaffold_wrapper.sh && ./skaffold_wrapper.sh -p production skaffold deploy --build-artifacts=skaffold-images.json
        env:
          KUBERNETES_TOKEN: ${{ secrets.KUBERNETES_TOKEN_PRODUCTION }}
          KUBERNETES_API_SERVER: ${{ secrets.KUBERNETES_API_SERVER }}
          KUBERNETES_CA: ${{ secrets.KUBERNETES_CA }}
